### PR TITLE
Fix typos; Reword some parts of the text

### PR DESCRIPTION
**Pull request by namannimmo10**
Ran the text through Grammarly. Hope this helps, @moorepants.

### CODE REVIEW

**Comment by moorepants** [comment]
Naman, here are the things I took from your PR: 8210783

**Comment by namannimmo10** [comment]
Thanks. Grammarly could still be useful if you don't want to hunt for typos manually. I guess I probably selected the formal text option, that's why it made some pointless changes.

**Comment by moorepants** [comment]
I'll probably be opinionated about this because the text is written by me and it should feel like me, errors and all. Something like grammarly can be a bit over zealous in what it recommends when you personally may be ok with some grammar variations. The main things I'd like feedback on are clarity of concepts. If my grammar decreases the clarity of the ideas, then it should be fixed.

**Comment by namannimmo10** [comment]
That makes sense!

**Pull request closed without merging**
