### PR TITLE
Update holonomic constraints chapter for 2023

### PR DESCRIPTION
**Pull request by moorepants**
- Added exercise of Watt's linkage.
- Added how to solve the constraints numerically with SymPy.

### CODE REVIEW

**Comment by moorepants** [comment]
This is ready for review. Peter, it seems that the preview link above works again so you can see the rendered version.

**Comment by Peter230655** [comment]
Yes, working again.

**Comment by moorepants** [comment]
This is one issue that could be addressed now https://github.com/moorepants/learn-multibody-dynamics/issues/97, but I may not have time to do so before the release at 17:00.

**Comment by moorepants** [comment]
I'm merging this. Feel free to give feedback here later.

**Comment by Peter230655** [comment]
There is a discussion going on between Timo and 'wwolfie', whether in your equation (70) point O must be fixed in frame A or not. wwolfie's proof looks reasonable to me, but I am not sure as he introduced a frame F, maybe a typo.
Should it be mentioned there, that point O must be fixed (or not fixed, whatever is right)?

**Comment by Peter230655** [comment]
Above the NOTE: Sympy mechanics has no way of knowing....
you write O.set_vel(N, 0)
Timo once told me, that one should not write O.set_vel(N, 0**.**)
Is this worth mentioning?

**Comment by Peter230655** [comment]
_Note
Sympy mechanics has no way of knowing..._
I think, this is so, because Newton's equations are the same, whether a frame is at rest or in uniform motion.
Is this not even an axiom of Newton's mechanics?
If so, is it worth mentioning?

**Comment by Peter230655** [comment]
Below eq (92) you write:
_We include t as it is possible that the constraint is an explicit function of time (instead of only implicit, as seen above in the four-bar linkage example)._
I guess an example of t being explicit in the constraints would be if we let, say, l_n = l_n * ( 1 + 1/2 * sin( alpha * t))

**Comment by Peter230655** [comment]
Above eq (97) you write:
_Our holonomic constraints dictate that there is no relative motion between points or reference frames_,
There is no relative motion between, say, P1 and P2, but is there not a relative motion possible between P1 and P3, or P2 and P4?

**Comment by Peter230655** [comment]
This is only for my personal education: you write:
_t = me.dynamicsymbols._t_
In my examples, I always use t = sm.symbols('t'), and this seems to work.
What is the advantage of your way of defining t ?
Thanks!

**Comment by Peter230655** [comment]
Above eq (84) you write:
_The case of Fig. 22 there are two vector paths to point P4 from point P1._..
Would it be (very slightly!) better to refer to Fig 22 a.)  ?

**Pull request merged**
